CREATE TABLE  "APLIC_IMPUTAC_PREVISION" 
   (	"ID_APLIC_IMPUTAC_PREVISION" NUMBER(6,0) NOT NULL ENABLE, 
	"SP" NUMBER(6,0) NOT NULL ENABLE, 
	"SECCION" NUMBER(4,0) NOT NULL ENABLE, 
	"SERVICIO" NUMBER(4,0) NOT NULL ENABLE, 
	"PROGRAMA" VARCHAR2(5) NOT NULL ENABLE, 
	"CONCEPTO" NUMBER(10,0) NOT NULL ENABLE, 
	"PROYECTO_INVERSION" VARCHAR2(30) NOT NULL ENABLE, 
	 CONSTRAINT "APLIC_IMPUTAC_PREVISION_PK" PRIMARY KEY ("ID_APLIC_IMPUTAC_PREVISION") ENABLE
   )
/
CREATE TABLE  "ATRIBUTOS_PREVISION" 
   (	"ID_ATRIBUTO_PREVISION" NUMBER(6,0) NOT NULL ENABLE, 
	"TIPO_ATRIBUTO_PREVISION" VARCHAR2(20) NOT NULL ENABLE, 
	"VALOR" VARCHAR2(100) NOT NULL ENABLE, 
	"SP" NUMBER(6,0) NOT NULL ENABLE, 
	 CONSTRAINT "ATRIBUTOS_PREVISION_PK" PRIMARY KEY ("ID_ATRIBUTO_PREVISION") ENABLE
   )
/
CREATE TABLE  "CAJAS_FIJA" 
   (	"CAJA_FIJA" NUMBER(5,0) NOT NULL ENABLE, 
	"SECCION" VARCHAR2(4) NOT NULL ENABLE, 
	"SERVICIO" VARCHAR2(4) NOT NULL ENABLE, 
	"PROGRAMA" VARCHAR2(5) NOT NULL ENABLE, 
	"CONCEPTO" VARCHAR2(10) NOT NULL ENABLE, 
	"ANO" NUMBER(4,0) NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(100) NOT NULL ENABLE, 
	"COMENTARIOS" VARCHAR2(1000), 
	"IMPORTE" NUMBER(10,0) NOT NULL ENABLE, 
	 CONSTRAINT "CAJAS_FIJA_PK" PRIMARY KEY ("CAJA_FIJA") ENABLE
   )
/
CREATE TABLE  "CONCEPTOS" 
   (	"CONCEPTO" NUMBER(10,0) NOT NULL ENABLE, 
	"VINCULANTE" NUMBER(5,0) NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(100) NOT NULL ENABLE, 
	 CONSTRAINT "CONCEPTOS_PK" PRIMARY KEY ("CONCEPTO") ENABLE
   )
/
CREATE TABLE  "DESTINATARIOS" 
   (	"DESTINATARIO" VARCHAR2(15) NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(100) NOT NULL ENABLE, 
	 CONSTRAINT "DESTINATARIOS_PK" PRIMARY KEY ("DESTINATARIO") ENABLE
   )
/
CREATE TABLE  "DISTRIBUCION_IMPUTACIONES" 
   (	"UA" NUMBER(6,0) NOT NULL ENABLE, 
	"NUM_LOTE" NUMBER(2,0) NOT NULL ENABLE, 
	"DESTINATARIO" VARCHAR2(15) NOT NULL ENABLE, 
	"PORCENTAJE" NUMBER(3,0) NOT NULL ENABLE, 
	 CONSTRAINT "DISTRIBUCION_IMPUTACIONES_PK" PRIMARY KEY ("UA", "NUM_LOTE", "DESTINATARIO") ENABLE
   )
/
CREATE TABLE  "DISTRIBUCION_PREVISION" 
   (	"SP" NUMBER(6,0) NOT NULL ENABLE, 
	"DESTINATARIO" VARCHAR2(15) NOT NULL ENABLE, 
	"PORCENTAJE" NUMBER(3,0) NOT NULL ENABLE, 
	 CONSTRAINT "DISTRIBUCION_PREVISION_PK" PRIMARY KEY ("SP", "DESTINATARIO") ENABLE
   )
/
CREATE TABLE  "DOCUMENTOS_CAJA_FIJA" 
   (	"CAJA_FIJA" NUMBER(5,0) NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(50) NOT NULL ENABLE, 
	"TIPO_DOCUMENTO" VARCHAR2(20) NOT NULL ENABLE, 
	"FICHERO" BLOB NOT NULL ENABLE, 
	"COMENTARIOS" VARCHAR2(200), 
	"MIME_TYPE_COLUMN" VARCHAR2(50), 
	"FILENAME_COLUMN" VARCHAR2(200), 
	"LAST_UPDATED_COLUMN" DATE, 
	"CHARACTER_SET_COLUMN" VARCHAR2(40), 
	 CONSTRAINT "DOCUMENTOS_CAJA_FIJA_PK" PRIMARY KEY ("CAJA_FIJA", "NOMBRE") ENABLE
   )
/
CREATE TABLE  "DOCUMENTOS_CONTRATACION" 
   (	"NUM_DOCUMENTO" NUMBER(10,0) NOT NULL ENABLE, 
	"UA" NUMBER(6,0) NOT NULL ENABLE, 
	"TIPO_DOCUMENTO" VARCHAR2(30) NOT NULL ENABLE, 
	"COMENTARIOS" VARCHAR2(1000), 
	"DOCUMENTO" BLOB NOT NULL ENABLE, 
	"MIME_TYPE_COLUMN" VARCHAR2(50), 
	"FILENAME_COLUMN" VARCHAR2(200), 
	"LAST_UPDATED_COLUMN" DATE, 
	"CHARACTER_SET_COLUMN" VARCHAR2(40), 
	 CONSTRAINT "DOCUMENTOS_CONTRATACION_PK" PRIMARY KEY ("NUM_DOCUMENTO") ENABLE
   )
/
CREATE TABLE  "DOCUMENTOS_FACTURACION" 
   (	"NUM_DOCUMENTO" NUMBER(6,0) NOT NULL ENABLE, 
	"ID_FACTURA" NUMBER(6,0) NOT NULL ENABLE, 
	"TIPO_DOCUMENTO_FAC" VARCHAR2(15) NOT NULL ENABLE, 
	"DOCUMENTACION" BLOB NOT NULL ENABLE, 
	"COMENTARIOS" VARCHAR2(1000), 
	"MIME_TYPE_COLUMN" VARCHAR2(50), 
	"FILENAME_COLUMN" VARCHAR2(200), 
	"LAST_UPDATED_COLUMN" DATE, 
	"CHARACTER_SET_COLUMN" VARCHAR2(40), 
	 CONSTRAINT "DOCUMENTOS_FACTURACION_PK" PRIMARY KEY ("NUM_DOCUMENTO") ENABLE
   )
/
CREATE TABLE  "DOCUMENTOS_MODELO" 
   (	"ID_MODELO" NUMBER(4,0) NOT NULL ENABLE, 
	"NUM_VERSION" NUMBER(3,0) NOT NULL ENABLE, 
	"DOCUMENTACION" BLOB NOT NULL ENABLE, 
	"COMENTARIOS" VARCHAR2(1000), 
	"MIME_TYPE_COLUMN" VARCHAR2(50), 
	"FILENAME_COLUMN" VARCHAR2(200), 
	"LAST_UPDATED_COLUMN" DATE, 
	"CHARACTER_SET_COLUMN" VARCHAR2(40), 
	 CONSTRAINT "DOCUMENTOS_MODELO_PK" PRIMARY KEY ("ID_MODELO", "NUM_VERSION") ENABLE
   )
/
CREATE TABLE  "DOCUMENTOS_MODIFICACIONES" 
   (	"ID_MODIFICACION" NUMBER(4,0) NOT NULL ENABLE, 
	"NUM_DOCUMENTO" NUMBER(4,0) NOT NULL ENABLE, 
	"TIPO_DOC_ENVIO" VARCHAR2(20) NOT NULL ENABLE, 
	"DOCUMENTACION" BLOB, 
	"COMENTARIOS" VARCHAR2(1000), 
	"MIME_TYPE_COLUMN" VARCHAR2(50), 
	"FILENAME_COLUMN" VARCHAR2(200), 
	"LAST_UPDATED_COLUMN" DATE, 
	"CHARACTER_SET_COLUMN" VARCHAR2(40), 
	 CONSTRAINT "DOCUMENTOS_MODIFICACIONES_PK" PRIMARY KEY ("ID_MODIFICACION", "NUM_DOCUMENTO") ENABLE
   )
/
CREATE TABLE  "EJERCICIOS_FUTUROS" 
   (	"TIPO_EJERCICIOS_FUTUROS" VARCHAR2(50) NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(200), 
	 CONSTRAINT "EJERCICIOS_FUTUROS_PK" PRIMARY KEY ("TIPO_EJERCICIOS_FUTUROS") ENABLE
   )
/
CREATE TABLE  "ESTADOS_PREVISION" 
   (	"ESTADO_PREVISION" VARCHAR2(15) NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(100), 
	 CONSTRAINT "ESTADOS_PREVISION_PK" PRIMARY KEY ("ESTADO_PREVISION") ENABLE
   )
/
CREATE TABLE  "EVENTOS_CONTRATACION" 
   (	"EVENTO" NUMBER(6,0) NOT NULL ENABLE, 
	"UA" NUMBER(6,0) NOT NULL ENABLE, 
	"TIPO_EVENTO_CONTRATACION" VARCHAR2(20) NOT NULL ENABLE, 
	"FECHA_INICIO" DATE NOT NULL ENABLE, 
	"FECHA_ESPERADA_FIN" DATE NOT NULL ENABLE, 
	"ID_TRAMITADOR" VARCHAR2(6) NOT NULL ENABLE, 
	"FECHA_FIN" DATE, 
	"COMENTARIO" VARCHAR2(1000) NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(100) NOT NULL ENABLE, 
	 CONSTRAINT "EVENTOS_CONTRATACION_PK" PRIMARY KEY ("EVENTO") ENABLE
   )
/
CREATE TABLE  "EVENTOS_FACTURACION" 
   (	"EVENTO" NUMBER(6,0) NOT NULL ENABLE, 
	"ID_FACTURA" NUMBER(6,0) NOT NULL ENABLE, 
	"TIPO_EVENTO_FACTURACION" VARCHAR2(20) NOT NULL ENABLE, 
	"FECHA_INICIO" DATE NOT NULL ENABLE, 
	"FECHA_ESPERADA_FIN" DATE NOT NULL ENABLE, 
	"ID_TRAMITADOR" VARCHAR2(6) NOT NULL ENABLE, 
	"FECHA_FIN" DATE, 
	"COMENTARIOS" VARCHAR2(1000) NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(100) NOT NULL ENABLE, 
	 CONSTRAINT "EVENTOS_FACTURACION_PK" PRIMARY KEY ("EVENTO") ENABLE
   )
/
CREATE TABLE  "EVENTOS_PLANIFICACION" 
   (	"EVENTO" NUMBER(6,0) NOT NULL ENABLE, 
	"SP" NUMBER(6,0) NOT NULL ENABLE, 
	"TIPO_EVENTO_PLANIFICACION" VARCHAR2(20) NOT NULL ENABLE, 
	"FECHA_INICIO" DATE NOT NULL ENABLE, 
	"FECHA_ESPERADA_FIN" DATE NOT NULL ENABLE, 
	"FECHA_FIN" DATE, 
	"ID_TRAMITADOR" VARCHAR2(6) NOT NULL ENABLE, 
	"COMENTARIOS" VARCHAR2(1000), 
	"DESCRIPCION" VARCHAR2(100) NOT NULL ENABLE, 
	 CONSTRAINT "EVENTOS_PLANIFICACION_PK" PRIMARY KEY ("EVENTO") ENABLE
   )
/
CREATE TABLE  "EVEN_PROC_CONT" 
   (	"TIPO_EVENTO" VARCHAR2(100) NOT NULL ENABLE, 
	"PROC_CONT" VARCHAR2(100) NOT NULL ENABLE, 
	 CONSTRAINT "EVEN_PROC_CONT_PK" PRIMARY KEY ("TIPO_EVENTO", "PROC_CONT") ENABLE
   )
/
CREATE TABLE  "EXPEDIENTES" 
   (	"UA" NUMBER(6,0) NOT NULL ENABLE, 
	"SP" NUMBER(6,0) NOT NULL ENABLE, 
	"UA_PADRE" NUMBER(6,0), 
	"NUM_LOTE_PADRE" NUMBER(2,0), 
	"NOMBRE" VARCHAR2(100) NOT NULL ENABLE, 
	"PROC_CONTRATACION" VARCHAR2(100), 
	"RC_SOLICITADO" CHAR(1), 
	"ORGANO_CONTRATACION" VARCHAR2(6), 
	"TIPO_EJERCICIOS_FUTUROS" VARCHAR2(3), 
	"INICIO_TRAMITACION" DATE, 
	"TIPO_CONTRATACION" VARCHAR2(25), 
	"PROYECTO_INVERSION" VARCHAR2(15), 
	"ID_JC" VARCHAR2(15), 
	"ID_DGRCC" VARCHAR2(15), 
	"ID_DTIC" VARCHAR2(15), 
	"ID_FINANCIERA" VARCHAR2(15), 
	"TIPO_TRAMITACION" VARCHAR2(20), 
	"COMENTARIOS" VARCHAR2(1000), 
	"CANCELADO" CHAR(1), 
	 CONSTRAINT "EXPEDIENTES_PK" PRIMARY KEY ("UA") ENABLE
   )
/
CREATE TABLE  "FACTURAS" 
   (	"ID_FACTURA" NUMBER(4,0) NOT NULL ENABLE, 
	"PERIODO" VARCHAR2(30), 
	"NUM_FACTURA_EXTERNO" VARCHAR2(30), 
	"FECHA_FACTURA" DATE, 
	"FECHA_CERT" DATE, 
	"FECHA_PAGO" DATE, 
	"FECHA_DEV" DATE, 
	"PAGADOR" NUMBER(6,0), 
	"COMENTARIOS" VARCHAR2(1000), 
	"NUM_IMPUTACION" NUMBER(6,0), 
	 CONSTRAINT "FACTURAS_PK" PRIMARY KEY ("ID_FACTURA") ENABLE
   )
/
CREATE TABLE  "FUNCIONES" 
   (	"ALIAS_FUNCION" VARCHAR2(15) NOT NULL ENABLE, 
	"NOMBRE_FUNCION" VARCHAR2(50) NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(1000), 
	 CONSTRAINT "FUNCIONES_PK" PRIMARY KEY ("ALIAS_FUNCION") ENABLE
   )
/
CREATE TABLE  "GENERADORES_INGRESO" 
   (	"ID_GENERADOR_INGRESO" NUMBER(4,0) NOT NULL ENABLE, 
	"SISTEMA" VARCHAR2(20), 
	"ORGANISMO" NUMBER(4,0), 
	"FECHA_FIRMA" DATE, 
	"FECHA_INICIO" DATE, 
	"FECHA_FIN" DATE, 
	"FECHA_FIN_PRORROGA" DATE, 
	"CONDICIONES_PRORROGA" VARCHAR2(1000), 
	"TIPO_LEGAL" VARCHAR2(20), 
	"EMAIL_ESPECIFICO" VARCHAR2(100), 
	"COMENTARIOS" VARCHAR2(1000), 
	"DOCUMENTO" BLOB, 
	"MIME_TYPE_COLUMN" VARCHAR2(50), 
	"FILENAME_COLUMN" VARCHAR2(200), 
	"LAST_UPDATED_COLUMN" DATE, 
	"CHARACTER_SET_COLUMN" VARCHAR2(40), 
	 CONSTRAINT "GENERADORES_INGRESO_PK" PRIMARY KEY ("ID_GENERADOR_INGRESO") ENABLE
   )
/
CREATE UNIQUE INDEX  "APLIC_IMPUTAC_PREVISION_PK" ON  "APLIC_IMPUTAC_PREVISION" ("ID_APLIC_IMPUTAC_PREVISION")
/
CREATE UNIQUE INDEX  "ATRIBUTOS_PREVISION_PK" ON  "ATRIBUTOS_PREVISION" ("ID_ATRIBUTO_PREVISION")
/
CREATE UNIQUE INDEX  "CAJAS_FIJA_PK" ON  "CAJAS_FIJA" ("CAJA_FIJA")
/
CREATE UNIQUE INDEX  "CONCEPTOS_PK" ON  "CONCEPTOS" ("CONCEPTO")
/
CREATE UNIQUE INDEX  "DESTINATARIOS_PK" ON  "DESTINATARIOS" ("DESTINATARIO")
/
CREATE UNIQUE INDEX  "DISTRIBUCION_IMPUTACIONES_PK" ON  "DISTRIBUCION_IMPUTACIONES" ("UA", "NUM_LOTE", "DESTINATARIO")
/
CREATE UNIQUE INDEX  "DISTRIBUCION_PREVISION_PK" ON  "DISTRIBUCION_PREVISION" ("SP", "DESTINATARIO")
/
CREATE UNIQUE INDEX  "DOCUMENTOS_CAJA_FIJA_PK" ON  "DOCUMENTOS_CAJA_FIJA" ("CAJA_FIJA", "NOMBRE")
/
CREATE UNIQUE INDEX  "DOCUMENTOS_CONTRATACION_PK" ON  "DOCUMENTOS_CONTRATACION" ("NUM_DOCUMENTO")
/
CREATE UNIQUE INDEX  "DOCUMENTOS_FACTURACION_PK" ON  "DOCUMENTOS_FACTURACION" ("NUM_DOCUMENTO")
/
CREATE UNIQUE INDEX  "DOCUMENTOS_MODELO_PK" ON  "DOCUMENTOS_MODELO" ("ID_MODELO", "NUM_VERSION")
/
CREATE UNIQUE INDEX  "DOCUMENTOS_MODIFICACIONES_PK" ON  "DOCUMENTOS_MODIFICACIONES" ("ID_MODIFICACION", "NUM_DOCUMENTO")
/
CREATE UNIQUE INDEX  "EJERCICIOS_FUTUROS_PK" ON  "EJERCICIOS_FUTUROS" ("TIPO_EJERCICIOS_FUTUROS")
/
CREATE UNIQUE INDEX  "ESTADOS_PREVISION_PK" ON  "ESTADOS_PREVISION" ("ESTADO_PREVISION")
/
CREATE UNIQUE INDEX  "EVENTOS_CONTRATACION_PK" ON  "EVENTOS_CONTRATACION" ("EVENTO")
/
CREATE UNIQUE INDEX  "EVENTOS_FACTURACION_PK" ON  "EVENTOS_FACTURACION" ("EVENTO")
/
CREATE UNIQUE INDEX  "EVENTOS_PLANIFICACION_PK" ON  "EVENTOS_PLANIFICACION" ("EVENTO")
/
CREATE UNIQUE INDEX  "EVEN_PROC_CONT_PK" ON  "EVEN_PROC_CONT" ("TIPO_EVENTO", "PROC_CONT")
/
CREATE UNIQUE INDEX  "EXPEDIENTES_PK" ON  "EXPEDIENTES" ("UA")
/
CREATE UNIQUE INDEX  "FACTURAS_PK" ON  "FACTURAS" ("ID_FACTURA")
/
CREATE UNIQUE INDEX  "FUNCIONES_PK" ON  "FUNCIONES" ("ALIAS_FUNCION")
/
CREATE UNIQUE INDEX  "GENERADORES_INGRESO_PK" ON  "GENERADORES_INGRESO" ("ID_GENERADOR_INGRESO")
/
 CREATE SEQUENCE   "GENERADORES_INGRESO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "FACTURAS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "EXPEDIENTES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "EVENTOS_PLANIFICACION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "EVENTOS_FACTURACION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "EVENTOS_CONTRATACION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "DOCUMENTOS_FACTURACION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "DOCUMENTOS_CONTRATACION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "CAJAS_FIJA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "ATRIBUTOS_PREVISION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "APLIC_IMPUTAC_PREVISION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
CREATE OR REPLACE TRIGGER  "BI_GENERADORES_INGRESO" 
  before insert on "GENERADORES_INGRESO"               
  for each row  
begin   
  if :NEW."ID_GENERADOR_INGRESO" is null then 
    select "GENERADORES_INGRESO_SEQ".nextval into :NEW."ID_GENERADOR_INGRESO" from sys.dual; 
  end if; 
end; 

/
ALTER TRIGGER  "BI_GENERADORES_INGRESO" ENABLE
/
CREATE OR REPLACE TRIGGER  "BI_FACTURAS" 
  before insert on "FACTURAS"               
  for each row  
begin   
  if :NEW."ID_FACTURA" is null then 
    select "FACTURAS_SEQ".nextval into :NEW."ID_FACTURA" from sys.dual; 
  end if; 
end; 

/
ALTER TRIGGER  "BI_FACTURAS" ENABLE
/
CREATE OR REPLACE TRIGGER  "BI_EXPEDIENTES" 
  before insert on "EXPEDIENTES"               
  for each row  
begin   
  if :NEW."UA" is null then 
    select "EXPEDIENTES_SEQ".nextval into :NEW."UA" from sys.dual; 
  end if; 
end; 

/
ALTER TRIGGER  "BI_EXPEDIENTES" ENABLE
/
CREATE OR REPLACE TRIGGER  "BI_EVENTOS_PLANIFICACION" 
  before insert on "EVENTOS_PLANIFICACION"               
  for each row  
begin   
  if :NEW."EVENTO" is null then 
    select "EVENTOS_PLANIFICACION_SEQ".nextval into :NEW."EVENTO" from sys.dual; 
  end if; 
end; 

/
ALTER TRIGGER  "BI_EVENTOS_PLANIFICACION" ENABLE
/
CREATE OR REPLACE TRIGGER  "BI_EVENTOS_FACTURACION" 
  before insert on "EVENTOS_FACTURACION"               
  for each row  
begin   
  if :NEW."EVENTO" is null then 
    select "EVENTOS_FACTURACION_SEQ".nextval into :NEW."EVENTO" from sys.dual; 
  end if; 
end; 

/
ALTER TRIGGER  "BI_EVENTOS_FACTURACION" ENABLE
/
CREATE OR REPLACE TRIGGER  "BI_EVENTOS_CONTRATACION" 
  before insert on "EVENTOS_CONTRATACION"               
  for each row  
begin   
  if :NEW."EVENTO" is null then 
    select "EVENTOS_CONTRATACION_SEQ".nextval into :NEW."EVENTO" from sys.dual; 
  end if; 
end; 

/
ALTER TRIGGER  "BI_EVENTOS_CONTRATACION" ENABLE
/
CREATE OR REPLACE TRIGGER  "BI_DOCUMENTOS_FACTURACION" 
  before insert on "DOCUMENTOS_FACTURACION"               
  for each row  
begin   
  if :NEW."NUM_DOCUMENTO" is null then 
    select "DOCUMENTOS_FACTURACION_SEQ".nextval into :NEW."NUM_DOCUMENTO" from sys.dual; 
  end if; 
end; 

/
ALTER TRIGGER  "BI_DOCUMENTOS_FACTURACION" ENABLE
/
CREATE OR REPLACE TRIGGER  "BI_DOCUMENTOS_CONTRATACION" 
  before insert on "DOCUMENTOS_CONTRATACION"               
  for each row  
begin   
  if :NEW."NUM_DOCUMENTO" is null then 
    select "DOCUMENTOS_CONTRATACION_SEQ".nextval into :NEW."NUM_DOCUMENTO" from sys.dual; 
  end if; 
end; 

/
ALTER TRIGGER  "BI_DOCUMENTOS_CONTRATACION" ENABLE
/
CREATE OR REPLACE TRIGGER  "BI_CAJAS_FIJA" 
  before insert on "CAJAS_FIJA"               
  for each row  
begin   
  if :NEW."CAJA_FIJA" is null then 
    select "CAJAS_FIJA_SEQ".nextval into :NEW."CAJA_FIJA" from sys.dual; 
  end if; 
end; 

/
ALTER TRIGGER  "BI_CAJAS_FIJA" ENABLE
/
CREATE OR REPLACE TRIGGER  "BI_ATRIBUTOS_PREVISION" 
  before insert on "ATRIBUTOS_PREVISION"               
  for each row  
begin   
  if :NEW."ID_ATRIBUTO_PREVISION" is null then 
    select "ATRIBUTOS_PREVISION_SEQ".nextval into :NEW."ID_ATRIBUTO_PREVISION" from sys.dual; 
  end if; 
end; 

/
ALTER TRIGGER  "BI_ATRIBUTOS_PREVISION" ENABLE
/
CREATE OR REPLACE TRIGGER  "BI_APLIC_IMPUTAC_PREVISION" 
  before insert on "APLIC_IMPUTAC_PREVISION"               
  for each row  
begin   
  if :NEW."ID_APLIC_IMPUTAC_PREVISION" is null then 
    select "APLIC_IMPUTAC_PREVISION_SEQ".nextval into :NEW."ID_APLIC_IMPUTAC_PREVISION" from sys.dual; 
  end if; 
end; 

/
ALTER TRIGGER  "BI_APLIC_IMPUTAC_PREVISION" ENABLE
/
